// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDruYJCF8g84ZXzUJRYZvdYeGcvXwILFKA',
    appId: '1:241623003531:web:63daba639a0d802732ff8e',
    messagingSenderId: '241623003531',
    projectId: 'cheonhong-studio',
    authDomain: 'cheonhong-studio.firebaseapp.com',
    storageBucket: 'cheonhong-studio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIqOJ2Qh_wdwa8ZxVVzjZB-MecWjnog68',
    appId: '1:241623003531:android:b27e90816d5c2ba832ff8e',
    messagingSenderId: '241623003531',
    projectId: 'cheonhong-studio',
    storageBucket: 'cheonhong-studio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL3ig1sR0f8kWBQj5pezl6Y5sKUAU4fc4',
    appId: '1:241623003531:ios:9a5e454763e54c2232ff8e',
    messagingSenderId: '241623003531',
    projectId: 'cheonhong-studio',
    storageBucket: 'cheonhong-studio.firebasestorage.app',
    iosClientId: '241623003531-bp5fiksr0oue31iuofe4j6mp2j8ki92t.apps.googleusercontent.com',
    iosBundleId: 'com.cheonhong.cheonhongStudio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL3ig1sR0f8kWBQj5pezl6Y5sKUAU4fc4',
    appId: '1:241623003531:ios:9a5e454763e54c2232ff8e',
    messagingSenderId: '241623003531',
    projectId: 'cheonhong-studio',
    storageBucket: 'cheonhong-studio.firebasestorage.app',
    iosClientId: '241623003531-bp5fiksr0oue31iuofe4j6mp2j8ki92t.apps.googleusercontent.com',
    iosBundleId: 'com.cheonhong.cheonhongStudio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDruYJCF8g84ZXzUJRYZvdYeGcvXwILFKA',
    appId: '1:241623003531:web:63daba639a0d802732ff8e',
    messagingSenderId: '241623003531',
    projectId: 'cheonhong-studio',
    authDomain: 'cheonhong-studio.firebaseapp.com',
    storageBucket: 'cheonhong-studio.firebasestorage.app',
  );

}